# Changes here will be overwritten by Copier
_commit: v2.0.2-19-g0d6a114
_src_path: gh:lincc-frameworks/python-project-template
author_email: olynn@andrew.cmu.edu
author_name: LINCC Frameworks
create_example_module: false
custom_install: true
enforce_style:
- ruff_lint
- ruff_format
failure_notification: []
include_benchmarks: true
include_docs: false
mypy_type_checking: none
package_name: tdastro
project_license: MIT
project_name: tdastro
project_organization: lincc-frameworks
python_versions:
- '3.9'
- '3.10'
- '3.11'
