import numpy as np
import pandas as pd
import pytest
from lightcurvelynx.noise_models.pzflow_noise_model import (
    PZFlowNoiseModel,
    _ColumnNormalizationData,
    learn_pzflow_noise_model,
)


def test_column_normalization_data():
    """Test that the _ColumnNormalizationData class correctly computes and applies
    normalization for a given column."""
    data = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
    data_normalizer = _ColumnNormalizationData(data, log_transform=False)

    norm_data = data_normalizer.normalize(data)
    assert np.allclose(norm_data, [0.0, 0.25, 0.5, 0.75, 1.0])

    round_trip_data = data_normalizer.denormalize(norm_data)
    assert np.allclose(round_trip_data, data)


def test_column_normalization_data_log_transform():
    """Test that the _ColumnNormalizationData class correctly computes and applies
    normalization for a given column with log transform."""
    data = np.array([0.1, 1.0, 2.0, 3.0, 4.0, 5.0, 100.0])
    data_normalizer = _ColumnNormalizationData(data, log_transform=True)

    norm_data = data_normalizer.normalize(data)
    expected_norm = np.array([0.0, 0.33333333, 0.43367667, 0.49237375, 0.53402, 0.56632333, 1.0])
    assert np.allclose(norm_data, expected_norm)

    round_trip_data = data_normalizer.denormalize(norm_data)
    assert np.allclose(round_trip_data, data)

    # We fail if we try to normalize data with non-positive values.
    with pytest.raises(ValueError, match="Data contains non-positive values"):
        _ColumnNormalizationData(np.array([-1.0, 1.0, 2.0]), log_transform=True)

    # We fail if we try to create a normalizer from non-positive values.
    with pytest.raises(ValueError, match="Data contains non-positive values"):
        _ColumnNormalizationData(np.array([0.0, 1.0, 2.0]), log_transform=True)


def test_column_normalization_data_invalid_input():
    """Test that the _ColumnNormalizationData class raises errors for invalid input."""
    with pytest.raises(ValueError, match="Data is empty"):
        _ColumnNormalizationData(np.array([]), log_transform=False)
    with pytest.raises(ValueError, match="Data contains only NaN values"):
        _ColumnNormalizationData(np.array([np.nan, np.nan, np.nan]), log_transform=False)
    with pytest.raises(ValueError, match="Data contains non-positive values"):
        _ColumnNormalizationData(np.array([0.0, -1.0, 2.0]), log_transform=True)


class LookupOnlyObsTable:
    """A simple dummy class to simulate the ObsTable's get_value_per_row method."""

    def __init__(self, table_values, const_values=None):
        self.table_values = pd.DataFrame(table_values)
        self.const_values = const_values or {}

    def get_value_per_row(self, key, indices, default=None):
        """Simulate the ObsTable's get_value_per_row method."""
        if key in self.table_values.columns:
            return np.asarray(self.table_values[key])[indices]
        if key in self.const_values:
            return np.full(len(indices), self.const_values[key])
        if default is not None:
            return np.full(len(indices), default)
        raise KeyError(f"Missing required key: {key}")


def test_pzflow_noise_model(test_data_dir):
    """Test that the PZFlowNoiseModel correctly computes flux errors
    and applies noise to the bandflux."""
    _ = pytest.importorskip("pzflow")

    # Create a fake ObsTable with zp (per row) and readnoise (constant) information
    # with a different column name for zp (to test name mapping).
    rng_for_data = np.random.default_rng(2024)
    num_samples = 20
    dummy_table = {"zp_vals": rng_for_data.normal(loc=25.0, scale=0.5, size=num_samples)}
    dummy_consts = {"readout_noise": 1.0}
    obs_table = LookupOnlyObsTable(dummy_table, const_values=dummy_consts)

    # Create a PZFlowNoiseModel using the flow file generated by
    # make_fake_noise_pzflow.py and mapping the "zp" input parameter to
    # the "zp_vals" column in the fake ObsTable.
    # This data is generated by the pzflow_noise_models.ipynb notebook.
    model = PZFlowNoiseModel.from_file(
        test_data_dir / "fake_noise_flow.pkl",
        input_col_map={"zp": "zp_vals"},
    )

    # Query the noise model.
    bandflux = np.linspace(400.0, 600.0, num_samples)

    rng_for_model = np.random.default_rng(2024)
    flux_out, flux_err = model.apply_noise(
        bandflux,
        obs_table=obs_table,
        indices=np.arange(num_samples),
        rng=rng_for_model,
    )
    assert len(flux_out) == num_samples
    assert len(flux_err) == num_samples

    diff = np.abs(flux_out - bandflux)
    assert np.all(diff > 0), "Expected some noise to be applied to the bandflux."
    assert np.all(flux_err > 0), "Expected positive flux errors."
    assert np.all(diff < 3 * flux_err), "Expected the noise to be within a few sigma."

    # We fail without an ObsTable, without indices, or with mismatched
    # indices length.
    with pytest.raises(ValueError, match="ObsTable must be provided"):
        model.apply_noise(bandflux, indices=np.arange(num_samples))
    with pytest.raises(ValueError, match="Indices must be provided"):
        model.apply_noise(bandflux, obs_table=obs_table)
    with pytest.raises(ValueError):
        model.apply_noise(
            bandflux,
            obs_table=obs_table,
            indices=np.arange(num_samples - 5),
        )


def test_learn_pzflow_noise_model():
    """Test that we can train a PZFlowNoiseModel on synthetic data and that it can
    learn to predict the flux errors."""
    rng = np.random.default_rng(2024)
    num_training_samples = 10_000

    # The input parameters for the pzflow model will be bandflux and zp.
    bandflux = rng.normal(loc=500.0, scale=100.0, size=num_training_samples)
    zp = rng.normal(loc=10.0, scale=0.15, size=num_training_samples)

    # This is the value the pzflow model is trained to predict.
    flux_err = np.sqrt(bandflux / zp) * zp

    training_data = pd.DataFrame({"bandflux": bandflux, "zp": zp, "flux_err": flux_err})
    noise_model = learn_pzflow_noise_model(training_data, noise_column="flux_err", normalize=True)
    assert isinstance(noise_model, PZFlowNoiseModel)
    assert noise_model._flow is not None

    # Check that we created the normalizers we need.
    assert isinstance(noise_model._normalizer_data["bandflux"], _ColumnNormalizationData)
    assert isinstance(noise_model._normalizer_data["zp"], _ColumnNormalizationData)
    assert isinstance(noise_model._normalizer_data["flux_err"], _ColumnNormalizationData)
