import numpy as np
import pandas as pd
import pytest
from lightcurvelynx.noise_models.pzflow_noise_model import PZFlowNoiseModel


class LookupOnlyObsTable:
    """A simple dummy class to simulate the ObsTable's get_value_per_row method."""

    def __init__(self, table_values, const_values=None):
        self.table_values = pd.DataFrame(table_values)
        self.const_values = const_values or {}

    def get_value_per_row(self, key, indices, default=None):
        """Simulate the ObsTable's get_value_per_row method."""
        if key in self.table_values.columns:
            return np.asarray(self.table_values[key])[indices]
        if key in self.const_values:
            return np.full(len(indices), self.const_values[key])
        if default is not None:
            return np.full(len(indices), default)
        raise KeyError(f"Missing required key: {key}")


def test_pzflow_noise_model(test_data_dir):
    """Test that the PZFlowNoiseModel correctly computes flux errors
    and applies noise to the bandflux."""
    rng_for_data = np.random.default_rng(2024)

    # Create a fake ObsTable with zp (per row) and readnoise (constant) information
    # with a different column name for zp (to test name mapping).
    num_samples = 20
    dummy_table = {"zp_vals": rng_for_data.normal(loc=25.0, scale=0.5, size=num_samples)}
    dummy_consts = {"readout_noise": 1.0}
    obs_table = LookupOnlyObsTable(dummy_table, const_values=dummy_consts)

    # Create a PZFlowNoiseModel using the flow file generated by
    # make_fake_noise_pzflow.py and mapping the "zp" input parameter to
    # the "zp_vals" column in the fake ObsTable.
    # This data is generated by the pzflow_noise_models.ipynb notebook.
    model = PZFlowNoiseModel.from_file(
        test_data_dir / "fake_noise_flow.pkl",
        input_col_map={"zp": "zp_vals"},
    )

    # Query the noise model.
    bandflux = np.linspace(400.0, 600.0, num_samples)

    rng_for_model = np.random.default_rng(2024)
    flux_out, flux_err = model.apply_noise(
        bandflux,
        obs_table=obs_table,
        indices=np.arange(num_samples),
        rng=rng_for_model,
    )
    assert len(flux_out) == num_samples
    assert len(flux_err) == num_samples

    diff = np.abs(flux_out - bandflux)
    assert np.all(diff > 0), "Expected some noise to be applied to the bandflux."
    assert np.all(flux_err > 0), "Expected positive flux errors."
    assert np.all(diff < 3 * flux_err), "Expected the noise to be within a few sigma."

    # We fail without an ObsTable, without indices, or with mismatched
    # indices length.
    with pytest.raises(ValueError, match="ObsTable must be provided"):
        model.apply_noise(bandflux, indices=np.arange(num_samples))
    with pytest.raises(ValueError, match="Indices must be provided"):
        model.apply_noise(bandflux, obs_table=obs_table)
    with pytest.raises(ValueError):
        model.apply_noise(
            bandflux,
            obs_table=obs_table,
            indices=np.arange(num_samples - 5),
        )
