import logging

from lightcurvelynx.consts import GAUSS_EFF_AREA2FWHM_SQ
from lightcurvelynx.obstable.obs_table import ObsTable

logger = logging.getLogger(__name__)


class DECamObsTable(ObsTable):
    """A subclass for DECam exposure table.

    Parameters
    ----------
    table : dict or pandas.core.frame.DataFrame
        The table with all the observation information.
    colmap : dict
        A mapping of standard column names to a list of possible names in the input table.
        Each value in the dictionary can be a string or a list of strings.
        Defaults to the DECam column names, stored in _default_colnames.
    saturation_mags : dict, optional
        A dictionary mapping filter names to their saturation thresholds in magnitudes. The filters
        provided must match those in the table. If not provided, DECam-specific defaults will be used.
    **kwargs : dict
        Additional keyword arguments to pass to the ObsTable constructor. This includes overrides
        for survey parameters such as:

        - dark_current : The dark current for the camera in electrons per second per pixel.
        - gain: The CCD gain (in e-/ADU).
        - pixel_scale: The pixel scale for the camera in arcseconds per pixel.
        - radius: The angular radius of the observations (in degrees).
        - read_noise: The standard deviation of the count of readout electrons per pixel.
    """

    # Default column names for the DECam survey data with data extracted from qcinv files.
    # See helper_tools/Build_DECAT_Dataset.ipynb for details on how these were derived.
    _default_colnames = {
        "maglim": "maglim",
        "sky": "sky",
        "dec": "dec",
        "exptime": "exptime",
        "filter": "filter",
        "ra": "ra",
        "time": "time",
        "zp": "zp",  # We add this column to the table
    }

    # Constant from the DECam camera specifications. See
    # https://noirlab.edu/science/programs/ctio/instruments/Dark-Energy-Camera/characteristics
    _default_survey_values = {
        "dark_current": 0.0,  # electrons per second per pixel
        "gain": 4.0,  # e-/ADU
        "pixel_scale": 0.263,  # arcseconds per pixel
        "radius": 1.1,  # degrees
        "read_noise": 7,  # electrons per pixel
        "zp_err_mag": 0,  # Place holder
        "survey_name": "unknown",  # DECAM supports many surveys
    }

    def __init__(
        self,
        table,
        colmap=None,
        saturation_mags=None,
        **kwargs,
    ):
        colmap = self._default_colnames if colmap is None else colmap

        super().__init__(
            table,
            colmap=colmap,
            saturation_mags=saturation_mags,
            **kwargs,
        )

    @classmethod
    def from_decat_survey(cls, table, filter_missing_data=True, **kwargs):
        """A class method to create a DECamObsTable from a DECAT survey table.

        This method assumes that the input table is in the format generated by the
        helper_tools/Build_DECAT_Dataset.ipynb, which includes the necessary columns
        with the correct names.

        Parameters
        ----------
        table : dict or pandas.core.frame.DataFrame
            The table with all the observation information.
        filter_missing_data : bool, optional
            If True, rows with any missing columns (usually the noise columns) will be dropped.
            Default is True.
        **kwargs : dict
            Additional keyword arguments to pass to the DECamObsTable constructor. This includes overrides
            for survey parameters such as:

            - dark_current : The dark current for the camera in electrons per second per pixel.
            - gain: The CCD gain (in e-/ADU).
            - pixel_scale: The pixel scale for the camera in arcseconds per pixel.
            - radius: The angular radius of the observations (in degrees).
            - read_noise: The standard deviation of the count of readout electrons per pixel.
        """
        decat_cols = ["ra", "dec", "time", "filter", "exptime", "secz", "psf", "sky", "cloud", "teff"]
        decat_set = set(decat_cols)
        col_set = set(table.columns)
        if not decat_set.issubset(col_set):
            missing_cols = decat_set - col_set
            raise ValueError(
                f"Input table is missing the following required columns for the DECAT survey: {missing_cols}"
            )

        logger.debug(f"Loading DECAT survey table with {len(table)} rows.")
        if filter_missing_data:
            logger.debug(f"Filtering out rows with missing data in the following columns: {decat_cols}")
            table = table.dropna(subset=decat_cols)
            logger.debug(f"After filtering, {len(table)} rows remain.")

        # Add some columns we need for noise.
        table.rename(columns={"secz": "airmass", "sky": "sky_bg_mag"}, inplace=True)

        # Compute the psf_footprint from the psf column, which is seeing in arcseconds.
        pixel_scale = kwargs.get("pixel_scale", cls._default_survey_values["pixel_scale"])
        table["psf_footprint"] = GAUSS_EFF_AREA2FWHM_SQ * (table["psf"] / pixel_scale) ** 2

        # Compute the zero point.

        # Compute the sky background in electrons per second per pixel.

        return cls(
            table,
            colmap=cls._default_colnames,
            saturation_mags=None,  # Use DECam-specific defaults if not provided
            **kwargs,
        )
